### PR TITLE
Decompile mouse.s

### PR DESCRIPTION
**Pull request by chmcl95**

### CODE REVIEW

**Comment by camthesaxman** [comment]
There are a few files here (such as code_9.c) that no longer exist on the master branch. I'm not sure how it got like that. Can you try merging master into this branch again?

**Comment by chmcl95** [comment]
> There are a few files here (such as code_9.c) that no longer exist on the master branch. I'm not sure how it got like that. Can you try merging master into this branch again?

Sure.
removed:
asm/nonmatchings/lbl_80076FA0.s
src/code_9.c

**Comment by camthesaxman** [comment]
Is this ready to merge?

**Comment by chmcl95** [comment]
Yes.
Those are ready to merge.

**Pull request merged**
