### PR TITLE
Separately compilable headers

### PR DESCRIPTION
**Pull request by ComplexPlane**
This PR adds header guards and #includes for all headers to make them independently compilable. The motivation is to allow use of static analysis/refactoring tools like clangd, so stuff like struct fields can be renamed quickly.

Also includes a script to generate a `compile_commands.json` which is needed by clangd as well.

I timed a full build before and after this change and got ~64s and ~65s respectively.

### CODE REVIEW

**Comment by camthesaxman** [comment]
Oh, cool! I've been wanting to do this for a while, especially for the dolphin system headers. The only thing I'm kind of iffy about is having game headers (the ones in src) include other headers, since it leads to lots of redundant includes.

How does this clang tool work for renaming struct fields? Being able to rename those easily would be very convenient.

**Comment by ComplexPlane** [comment]
> The only thing I'm kind of iffy about is having game headers (the ones in src) include other headers, since it leads to lots of redundant includes.

It seems that most game headers only include a couple Dolphin headers, though a few unfortunately require `types.h` at the moment. Splitting some stuff out of that header would make it unnecessary though. Also the include guards prevent any extra included headers from actually being compiled multiple times to be fair.

> How does this clang tool work for renaming struct fields?

Here I'm using the `clangd` extension for VSCode, you can press F2 to rename pretty much anything:

Code_FVFxMTtXX3

clangd supports lots of other editors though, maybe even the command line too.

**Comment by camthesaxman** [comment]
Looks good. Just fix the missing newlines, and I'll merge.

**Comment by ComplexPlane** [comment]
Sure thing, should be good now.

**Pull request merged**
